### PR TITLE
Update box used for testing

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Review by apatard — APPROVED** [review]
let's wait for the CI to see if this PR is enough to fix the checks

**Comment by konstruktoid** [comment]
https://github.com/pycontribs/python-vagrant/runs/5690559721?check_suite_focus=true#step:8:699
https://github.com/pycontribs/python-vagrant/runs/5690559721?check_suite_focus=true#step:8:1071

All Vagrantfiles need to be fixed as well, https://github.com/konstruktoid/python3-vagrant/commit/e1c805cde7a2043ab6748e91b5048d98562b5e64

**Review by konstruktoid — COMMENTED** [review]
https://github.com/pycontribs/python-vagrant/runs/5690559721?check_suite_focus=true#step:8:699
https://github.com/pycontribs/python-vagrant/runs/5690559721?check_suite_focus=true#step:8:1071

All Vagrantfiles need to be fixed as well, https://github.com/konstruktoid/python3-vagrant/commit/e1c805cde7a2043ab6748e91b5048d98562b5e64

**Comment by konstruktoid** [comment]
Updates in https://github.com/pycontribs/python-vagrant/pull/84

**Comment by apatard** [comment]
hm. Things are getting better I guess. There are about 4 failures due to nose removal (eq_, ok_, ...) and 2 due to setUpOnce() being broken (I've a possible fix for that). I've yet to analyse the other failures to see if they have to be fixed by this PR or should be done in an other PR.

**Comment by konstruktoid** [comment]
> hm. Things are getting better I guess. There are about 4 failures due to nose removal (eq_, ok_, ...) 

yeah, those are basically (easily fixed?) asserts.

Should we keep pushing PRs to this branch or  wait for merge and start anew?

**Comment by apatard** [comment]
> > hm. Things are getting better I guess. There are about 4 failures due to nose removal (eq_, ok_, ...)
> 
> yeah, those are basically (easily fixed?) asserts.
> 
> Should we keep pushing PRs to this branch or wait for merge and start anew?

since this PR is called "update box" I would say that this PR should be related only to the boxes changes and that the nose removal and setUpOnce() fixes should go into a different PR.

@ssbarnea any opinion ?

**Comment by konstruktoid** [comment]
> since this PR is called "update box" I would say that this PR should be related only to the boxes changes and that the nose removal and setUpOnce() fixes should go into a different PR.

makes sense

**Comment by ssbarnea** [comment]
I am going to merge this as is, even if we still have 9 failing tests, mainly to make it easier to review the other changes.

**Pull request merged**
