### PR TITLE
Adding `ssh` to Vagrant Class

### PR DESCRIPTION
**Pull request by kodelint**
This was the only option left. This will help me to write wrapper script and use the method.

### CODE REVIEW

**Comment by kodelint** [comment]
@todddeluca can you please take look at the PR ?

**Comment by retr0h** [comment]
Any update on this?  Is this project considered abandoned?

**Comment by todddeluca** [comment]
Forgive my ignorance but why do you want to invoke a bare `vagrant ssh` from python?

**Comment by uniqx** [comment]
@todddeluca wrote:
> Forgive my ignorance but why do you want to invoke a bare vagrant ssh from python?

We at [F-Droid](https://f-droid.org) use ssh to automate Android app builds inside vagrant VMs:
https://gitlab.com/fdroid/fdroidserver/-/blob/master/fdroidserver/build.py#L55

**Comment by ssbarnea** [comment]
Closing due to its age, but I would not be against such change, but still it would need a test.

**Pull request closed without merging**
